load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("//bazel:cc.bzl", "zig_c_wasm")

package(default_visibility = ["//visibility:public"])

zig_c_wasm(
    name = "wasi_parse_wasm",
    srcs = [
        "wasi_parse.c",
        "//grammars:parser_csrcs",
        "//grammars:scanners",
        "@tree_sitter//:runtime_c",
    ],
    copts = [
        "-std=c11",
        "-D_POSIX_C_SOURCE=200112L",
        "-D_DEFAULT_SOURCE",
    ],
    extra_srcs = [
        "@tree_sitter//:runtime_support",
        "@tree_sitter//:runtime_header_files",
    ],
    linkopts = ["-lc"],
    out = "wasi_parse_wasm.wasm",
    target = "wasm32-wasi",
    deps = ["@tree_sitter//:headers"],
)

sh_test(
    name = "wasi_parse_test",
    srcs = ["wasi_parse_test.sh"],
    args = [
        "$(location @wasmtime//:wasmtime)",
        "$(location :wasi_parse_wasm)",
    ],
    data = [
        ":wasi_parse_wasm",
        "@wasmtime//:wasmtime",
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
)
