load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "backend",
    srcs = ["src/lib.rs"],
    crate_name = "twigz_backend",
    edition = "2021",
    deps = [
        "//crates/ir",
        "@crates//:serde_json",
    ],
)
